<?php
include('../Model/UserModel.php');
include('../Model/ShiftsModel.php');
include('../Model/Dbh.php');
include('../Controller/session.php');
include('../Controller/UserController.php');
include('../Controller/shifts.php');
include('../DTO/User.php');
include('../DTO/AssignedShift.php');
include('../DTO/Availability.php');
?>